In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits() 

In [2]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()

In [4]:
lr.fit(x_train, y_train)
lr.score(x_test,y_test)

C:\Users\Yash Gore\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

In [5]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9925925925925926

In [6]:
rf = RandomForestClassifier()
rf.fit(x_train , y_train)
rf.score(x_test,y_test)

0.9777777777777777

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=8)
kf

KFold(n_splits=8, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [9]:
def get_score(model , x_train , x_tset , y_train , y_test):
    model.fit(x_train , y_train)
    return model.score(x_tset,y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [20]:
score_l = []
score_svm = []
score_rf = []

for train_index , test_index , in kf.splits(digits.data):
      X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                          digits.target[train_index], digits.target[test_index]
    
    print(get_score(LogisticRegression() , x_train , x_test , y_train , y_test))
    print(get_score(SVC() , x_train , x_test , y_train , y_test))
    print(get_score(RandomForestClassifier() , x_train , x_test , y_train , y_test))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)