In [1]:
import numpy as np

In [2]:
R = np.matrix([[-1,-1,-1,-1,0,-1],[-1,-1,-1,0,-1,100],[-1,-1,0,-1,-1,-1],[-1,0,0,-1,-1,-1],[0,-1,-1,0,-1,100]])

In [3]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,   0,  -1,  -1,  -1],
        [ -1,   0,   0,  -1,  -1,  -1],
        [  0,  -1,  -1,   0,  -1, 100]])

In [22]:
Q = np.matrix(np.zeros([6,6]))

In [23]:
gamma = 0.8

In [24]:
initial_state = 1

In [25]:
def available_action(state):
    current_state_row = R[state]
    av_act = np.where(current_state_row>=0)[1]
    return av_act

In [26]:
available_act = available_action(initial_state)

In [27]:
available_act

array([3, 5], dtype=int64)

In [28]:
def sample_next_action(avilable_action_range):
    next_action = int(np.random.choice(avilable_action_range,1))
    return next

In [29]:
action = sample_next_action(available_act)

In [56]:
def update(current_state , action , gamma):
    maxvalue = np.max(Q[action,])
    Q[current_state,action] = R[current_state,action]+gamma*maxvalue

In [57]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [58]:
initial_state

1

In [59]:
update(initial_state,action,gamma)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [60]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])